{% set name = "tpi" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 739b9c98a96ead6a0b8b5d3d85afc4f56443ec1cc04a3e60abc08af4930830a5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tpi = tpi.main:main

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.4
    - sshfs >=2021.7.1
    - funcy
    - jinja2 >=2.0.0
    - miutil >=0.7.0
    - requests
    - python-terraform >=0.10.1
    - setuptools

test:
  imports:
    - tpi
    - tpi.bin
    - tpi.terraform
  commands:
    - tpi -h

about:
  home: https://github.com/iterative/tpi
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: Python wrapper for terraform-provider-iterative

  description: |
    Python wrapper for https://github.com/iterative/terraform-provider-iterative.
    Automatically downloads platform-dependent terraform binaries and exposes a Python API.

extra:
  recipe-maintainers:
    - casperdcl
    - shcheklein
